<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>War3Frame.Regression</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../War3Frame/War3Frame.csproj" />
    <ProjectReference Include="../../FrameBuild/War3FrameBuild.csproj" />
    <ProjectReference Include="../../FastMDX/FastMDX.csproj" />
    <ProjectReference Include="../../CSharpWar3Frame/CSharpWar3FrameConsole.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../../War3Frame.Generator/War3Frame.Generator.csproj" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.9.0" />
    <Compile Include="../test/Scripts/Process/*.cs" Link="ExistingScenarios/%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
