using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace War3Frame.Generator;

[Generator]
public sealed class SystemGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor Invalid = new("WFGEN003", "Invalid system registration", "System '{0}': {1}", "Registration", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor External = new("WFGEN004", "External system registration unsupported", "System '{0}' must join the framework's ordered registration; consumer SystemRegister cannot be appended after event cleanup", "Registration", DiagnosticSeverity.Error, true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var systems = context.SyntaxProvider.ForAttributeWithMetadataName("War3Frame.Systems.SystemRegisterAttribute",
            static (node, _) => node is ClassDeclarationSyntax,
            static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol).Collect();
        context.RegisterSourceOutput(context.CompilationProvider.Combine(systems),
            static (ctx, input) => Generate(ctx, input.Left, input.Right));
    }

    private static void Generate(SourceProductionContext context, Compilation compilation, ImmutableArray<INamedTypeSymbol> systems)
    {
        var attribute = compilation.GetTypeByMetadataName("War3Frame.Systems.SystemRegisterAttribute");
        if (attribute == null) return;
        var isRuntime = SymbolEqualityComparer.Default.Equals(attribute.ContainingAssembly, compilation.Assembly);
        var entries = systems.Distinct(SymbolEqualityComparer.Default).Cast<INamedTypeSymbol>().Select(s => new
        {
            Symbol = s,
            Type = s.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            Attribute = s.GetAttributes().First(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, attribute))
        }).Select(e => new
        {
            e.Symbol, e.Type,
            Kind = e.Attribute.ConstructorArguments[0].Value as int?,
            Order = e.Attribute.ConstructorArguments.Length > 1 ? (int)e.Attribute.ConstructorArguments[1].Value! : 1
        }).OrderBy(e => e.Order).ThenBy(e => e.Type, StringComparer.Ordinal);
        var output = new StringBuilder("// <auto-generated/>\n#nullable enable\nnamespace War3Frame;\npublic static partial class Game\n{\n    static partial void RegisterGeneratedSystems()\n    {\n");
        foreach (var entry in entries)
        {
            if (!isRuntime)
            {
                context.ReportDiagnostic(Diagnostic.Create(External, entry.Symbol.Locations.FirstOrDefault(), entry.Type));
                continue;
            }
            var error = RegistrationSymbols.ConstructionError(entry.Symbol, compilation);
            var current = entry.Symbol.BaseType;
            while (current != null && current.ToDisplayString() != "Friflo.Engine.ECS.Systems.BaseSystem") current = current.BaseType;
            if (current == null) error = "must derive from BaseSystem";
            if (entry.Kind is not (0 or 1)) error = "unsupported SystemKind";
            if (error != null)
            {
                context.ReportDiagnostic(Diagnostic.Create(Invalid, entry.Symbol.Locations.FirstOrDefault(), entry.Type, error));
                continue;
            }
            output.Append("        Root.Add(new ").Append(entry.Type).Append(entry.Kind == 1 ? "(), 0f);\n" : "());\n");
        }
        output.Append("    }\n}\n");
        if (isRuntime) context.AddSource("Game.SystemRegistration.g.cs", SourceText.From(output.ToString(), Encoding.UTF8));
    }
}
