using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace War3Frame.Generator;

// friflo system批量注册
[Generator]
public class SystemGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        const string fullName = "War3Frame.Systems.SystemRegisterAttribute";
        var sytemInfo = context.SyntaxProvider.ForAttributeWithMetadataName(fullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: (ctx, _) => GetSystemInfo(ctx, fullName))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!.Value);

        var collectedSystems = sytemInfo.Collect();
        context.RegisterSourceOutput(collectedSystems,
            (ctx, systems) => GenerateRegistrationCode(ctx, systems));
    }

    public readonly struct SystemInfo
    {
        public SystemInfo(string className, string @namespace, string kind, int order)
        {
            ClassName = className;
            Namespace = @namespace;
            Kind = kind;
            Order = order;
        }

        public string ClassName { get; }
        public string Namespace { get; }
        public string Kind { get; }
        public int Order { get; }
    }

    public static SystemInfo? GetSystemInfo(GeneratorAttributeSyntaxContext ctx, string fullName)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol classSymbol)
            return null;

        var attributeData = ctx.Attributes.FirstOrDefault(a =>
            a.AttributeClass?.ToDisplayString() == fullName);

        if (attributeData is null)
            return null;

        if (attributeData.ConstructorArguments.Length == 0)
            return null;

        var kindArg = attributeData.ConstructorArguments[0];
        var kind = kindArg.Value?.ToString();

        var order = 1;
        if (attributeData.ConstructorArguments.Length > 1 &&
            attributeData.ConstructorArguments[1].Value is IConvertible value)
        {
            order = value.ToInt32(System.Globalization.CultureInfo.InvariantCulture);
        }

        return new SystemInfo(
            classSymbol.ToDisplayString(),
            classSymbol.ContainingNamespace.ToDisplayString(),
            kind ?? "",
            order);
    }

    /// <summary>
    /// 生成 System 注册代码
    /// </summary>
    private static void GenerateRegistrationCode(
        SourceProductionContext context,
        ImmutableArray<SystemInfo> systemInfos)
    {
        if (systemInfos.Length == 0)
            return;

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Friflo.Engine.ECS;");
        sb.AppendLine("using Friflo.Engine.ECS.Systems;");
        sb.AppendLine();

        var namespaces = systemInfos
            .Select(t => t.Namespace)
            .Distinct()
            .OrderBy(n => n);

        foreach (var ns in namespaces)
        {
            if (!string.IsNullOrEmpty(ns) && ns != "global")
            {
                sb.AppendLine($"using {ns};");
            }
        }

        sb.AppendLine();
        sb.AppendLine("namespace War3Frame;");
        sb.AppendLine();
        sb.AppendLine("public static partial class Game");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 自动注册所有标记的 System");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    static partial void RegisterGeneratedSystems()");
        sb.AppendLine("    {");

        foreach (var systemInfo in systemInfos.OrderBy(t => t.Order)
                     .ThenBy(t => t.ClassName, StringComparer.Ordinal))
        {
            var rootName = systemInfo.Kind == "Immediate" ? "ImmediateRoot" : "Root";
            sb.AppendLine($"        {rootName}.Add(new {systemInfo.ClassName}());");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("Game.SystemRegistration.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}