using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace War3Frame.Generator;

/// <summary>框架生成 partial 注册；消费者生成独立、显式调用的本程序集 registrar。</summary>
[Generator]
public sealed class UnitTemplateGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor Invalid = new("WFGEN001", "Invalid template", "Template '{0}': {1}", "Registration", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor Duplicate = new("WFGEN002", "Duplicate template name", "Duplicate {0} name '{1}' in this assembly", "Registration", DiagnosticSeverity.Error, true);
    private static readonly string[] Registries = { "UnitTemplate", "AbilityTemplate", "ItemTemplate" };

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classes = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
            static (ctx, _) => ctx.SemanticModel.GetDeclaredSymbol((ClassDeclarationSyntax)ctx.Node) as INamedTypeSymbol)
            .Where(static symbol => symbol != null).Collect();
        context.RegisterSourceOutput(context.CompilationProvider.Combine(classes),
            static (ctx, input) => Generate(ctx, input.Left, input.Right));
    }

    private static void Generate(SourceProductionContext context, Compilation compilation, ImmutableArray<INamedTypeSymbol?> classes)
    {
        var registry = compilation.GetTypeByMetadataName("War3Frame.TemplateInit.UnitTemplate");
        if (registry == null) return;
        var isRuntime = SymbolEqualityComparer.Default.Equals(registry.ContainingAssembly, compilation.Assembly);
        var entries = classes.Where(c => c != null).Cast<INamedTypeSymbol>()
            .GroupBy(c => c.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), StringComparer.Ordinal)
            .Select(g => g.First()).SelectMany(c => c.GetAttributes().Select(a => new { Symbol = c, Attribute = a }))
            .Where(e => Registries.Any(r => e.Attribute.AttributeClass?.ToDisplayString() == "War3Frame.TemplateInit." + r + "Attribute"))
            .Select(e => new
            {
                e.Symbol,
                Registry = e.Attribute.AttributeClass!.Name.Replace("Attribute", ""),
                Name = e.Attribute.ConstructorArguments.FirstOrDefault().Value as string,
                Type = e.Symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            }).OrderBy(e => e.Registry, StringComparer.Ordinal).ThenBy(e => e.Name, StringComparer.Ordinal).ThenBy(e => e.Type, StringComparer.Ordinal).ToArray();
        var valid = new System.Collections.Generic.List<(string Registry, string Name, string Type)>();
        foreach (var entry in entries)
        {
            var error = RegistrationSymbols.ConstructionError(entry.Symbol, compilation);
            var contract = compilation.GetTypeByMetadataName("War3Frame.TemplateInit.I" + entry.Registry);
            if (string.IsNullOrWhiteSpace(entry.Name)) error = "name must not be empty";
            else if (!entry.Symbol.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, contract)))
                error = "must implement I" + entry.Registry;
            else if (entry.Registry == "AbilityTemplate" && entry.Name!.StartsWith("__item_inline__:", StringComparison.Ordinal))
                error = "name uses a reserved framework prefix";
            if (error != null)
            {
                context.ReportDiagnostic(Diagnostic.Create(Invalid, entry.Symbol.Locations.FirstOrDefault(), entry.Type, error));
                continue;
            }
            if (entries.Count(e => e.Registry == entry.Registry && e.Name == entry.Name) > 1)
            {
                context.ReportDiagnostic(Diagnostic.Create(Duplicate, entry.Symbol.Locations.FirstOrDefault(), entry.Registry, entry.Name));
                continue;
            }
            valid.Add((entry.Registry, entry.Name!, entry.Type));
        }

        if (isRuntime)
        {
            foreach (var kind in Registries)
            {
                var code = new StringBuilder("// <auto-generated/>\n#nullable enable\nnamespace War3Frame.TemplateInit;\n");
                code.Append("public static partial class ").Append(kind).Append("\n{\n    static partial void RegisterGenerated()\n    {\n");
                foreach (var entry in valid.Where(e => e.Registry == kind))
                    code.Append("        Register(").Append(SymbolDisplay.FormatLiteral(entry.Name, true)).Append(", new ").Append(entry.Type).Append("());\n");
                code.Append("    }\n}\n");
                context.AddSource(kind + ".g.cs", SourceText.From(code.ToString(), Encoding.UTF8));
            }
            return;
        }

        var output = new StringBuilder("// <auto-generated/>\n#nullable enable\nnamespace War3Frame.Generated;\ninternal static class ProjectTemplateRegistration\n{\n    private static bool _initialized;\n    internal static void Initialize()\n    {\n        if (_initialized) return;\n");
        foreach (var kind in Registries)
            output.Append("        global::War3Frame.TemplateInit.").Append(kind).Append(".Initialize();\n");
        // 完成全部构造后才写注册表，构造失败可重试，不留下部分项目模板。
        for (var i = 0; i < valid.Count; i++)
            output.Append("        var template").Append(i).Append(" = new ").Append(valid[i].Type).Append("();\n");
        for (var i = 0; i < valid.Count; i++)
            output.Append("        global::War3Frame.TemplateInit.").Append(valid[i].Registry).Append(".Register(")
                .Append(SymbolDisplay.FormatLiteral(valid[i].Name, true)).Append(", template").Append(i).Append(");\n");
        output.Append("        _initialized = true;\n    }\n}\n");
        context.AddSource("ProjectTemplateRegistration.g.cs", SourceText.From(output.ToString(), Encoding.UTF8));
    }
}

internal static class RegistrationSymbols
{
    internal static string? ConstructionError(INamedTypeSymbol type, Compilation compilation)
    {
        if (type.IsAbstract || type.IsStatic) return "must be a concrete class";
        for (var current = type; current != null; current = current.ContainingType)
            if (current.Arity != 0 || current.IsFileLocal) return "generic or file-local types cannot be registered";
        if (!compilation.IsSymbolAccessibleWithin(type, compilation.Assembly)) return "type is inaccessible from generated registration";
        if (!type.InstanceConstructors.Any(c => c.Parameters.Length == 0 && compilation.IsSymbolAccessibleWithin(c, compilation.Assembly)))
            return "an accessible parameterless constructor is required";
        return null;
    }
}
