<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>War3Frame</RootNamespace>
        <AssemblyName>project</AssemblyName>

        <RuntimeIdentifier>win-x86</RuntimeIdentifier>
        <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <PropertyGroup Condition="'$(PublishAot)' == 'true'">
        <DefineConstants>$(DefineConstants);WAR3FRAME_NATIVE_AOT</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Library\"/>
        <Folder Include="Scripts\Setup\"/>
        <Folder Include="Scripts\Process\"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\War3Frame\War3Frame.csproj" Aliases="global,War3FrameRuntime"/>
        <TrimmerRootAssembly Include="Friflo.Engine.ECS"/>
    </ItemGroup>

</Project>
